name: habla_conmigo
description: A Flutter application to help you practice speaking Spanish through interactive conversations.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  speech_to_text: ^6.5.1
  flutter_tts: ^3.8.5
  uuid: ^4.1.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  flutter_svg: ^2.0.9
  audioplayers: ^5.2.1
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700