name: habla_conmigo
description: A Flutter application to help you practice speaking Spanish through interactive conversations.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  provider: ^6.1.5
  uuid: ^4.5.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_svg: ^2.1.0
  audioplayers: ^6.4.0
  vapinew: ^0.0.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # assets:
  #   - assets/images/

  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
  #       - asset: assets/fonts/Inter-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Inter-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Inter-Bold.ttf
  #         weight: 700